### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by palmieri** [robot-motion/bench-mr#1]
When trying to compile, following the readme instructions i receive the following issue:

➜  build git:(master) ✗  cmake ..
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'eigen3>=3'
-- Checking for one of the modules 'libccd;ccd'
-- Checking for one of the modules 'cairo'
CMake Error at CMakeLists.txt:21 (add_subdirectory):
  The source directory

    /home/user/mpb/params

  does not contain a CMakeLists.txt file.

-- Checking for module 'sbpl'
--   No package 'sbpl' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  CMakeLists.txt:36 (pkg_check_modules)

**Comment by eric-heiden** [comment]
The [params](https://github.com/eric-heiden/params) directory should contain a CMakeLists.txt file when you check out the git submodule. 

I will update the README with more installation steps, but for now all steps are also in the CircleCI [config.yml](https://github.com/eric-heiden/mpb/blob/master/.circleci/config.yml) which are running whenever something gets committed.

**Comment by palmieri** [comment]
Sorry, didn't pay attention to .circleci folder. 

For Ubuntu 16.04, other two issues are the missing package nlohmann-json-dev and "CMake Error at chomp/chomp/CMakeLists.txt:1 (add_library):   CXX_STANDARD is set to invalid value '17'"
