### ISSUE TITLE
Add deterministic sampling

### ISSUE THREAD

**Issue by palmieri** [robot-motion/bench-mr#10]
**Why?**
Together with uniform sampling, we could include a comparison with deterministic sampling

**What?**
Add Halton deterministic sampling  This will work only with PRM* and FMT*

**Comment by roym899** [comment]
This should work for RRT too. I guess the main constraint right now is that planners can't rely on Gaussian sampling (or any other kind of biased sampling).

**Comment by roym899** [comment]
Addressed with #15
