### ISSUE TITLE
Fix SBPL

### ISSUE THREAD

**Issue by eric-heiden** [robot-motion/bench-mr#21]
Need to debug/generate motion primitives (scaling)

**Comment by palmieri** [comment]
Not yet solved. Possibly related to the scaling of the pol. based env.  Maybe related to not considering the resolution? 
Ideally we will need to have running it on at least 1 type of environment.

**Comment by palmieri** [comment]
Need to check:
- Interpolation for visualization, we don't have to use the steering function there
- Double check the interface to the sbpl

**Comment by eric-heiden** [comment]
Fixed in #26
