### ISSUE TITLE
CMakeLists Mistake when including gui sources

### ISSUE THREAD

**Issue by ksatyaki** [robot-motion/bench-mr#41]
Line [82 in main CMakeLists.txt](https://github.com/robot-motion/bench-mr/blob/640d9b91437a0dcb14aa79d1ad253bc548e2d7a7/CMakeLists.txt#L82) should be changed from:
``` file(GLOB GUI_SRC gui/*.?pp) ```
to 
``` file(GLOB GUI_SRC src/gui/*.?pp) ```

**Comment by eric-heiden** [comment]
Thanks for reporting this mistake! I fixed this now, but there may still be some errors when using these Qt GUI flags. Feel free to report any future bugs, we haven't tested the Qt GUI features in a long time.

**Comment by ksatyaki** [comment]
I see. I hope to extensively use Bench-MR for my work in the next few months. @palmieri is also involved! :-) 
I would be happy to share it with you guys as well. Let me know <a href="mailto:chittaranjan.swaminathan@oru.se">HERE</a>  if you are interested in my research and if you think you might want to contribute. :-)
