### ISSUE TITLE
Add new environments

### ISSUE THREAD

**Issue by palmieri** [robot-motion/bench-mr#7]
**Why?**
To further test the planning capabilities, we can expand the environments on which we test the planners

**What?**
Additional environments can be include:
- Add more warehouse like environments;
- include additional grids from existing datasets (from moving-ai, from [slam benchmarks](http://ais.informatik.uni-freiburg.de/slamevaluation/datasets.php) or [stachnis-web-page](http://www2.informatik.uni-freiburg.de/~stachnis/datasets.html))

--------
Update:

-- add procedural generation of polygon based environment (i.e. place random obst., varying corridor size)

**Comment by eric-heiden** [comment]
Working towards this goal from this branch that allows to load maps from image files:
https://github.com/eric-heiden/mpb/tree/feature/map_from_image
